### ISSUE TITLE
Introduction to Haskell

### ISSUE THREAD

**Issue by DecentralizedReality** [dostrelith678/hpm-education-haskell#2]
This is a repeat of the Introduction section.  Remove or change Introduction to Haskell section? 

Also, the italic descriptions of Haskell are mentioned they will be explored in more detail. 

Would be cool to have all these terms linked to the sections in the book where they are specifically covered.

**Comment by dostrelith678** [comment]
I agree and have noticed this, I think just removing that first page will be okay at least for now.

**Comment by dostrelith678** [comment]
It seems that there MUST be a landing page on GitBook that is not part of the `Introduction` group. So I have deleted the first page in the intro to avoid duplication.
