### ISSUE TITLE
Suggested remove sections

### ISSUE THREAD

**Issue by DecentralizedReality** [dostrelith678/hpm-education-haskell#5]
Perhaps we just remove "Pros and Cons" and "History of Haskell" sections.  This is basically a quickstart guide/ tutorial for people that want to get the most efficient and practical jump into Plutus development... maybe leave those to the other more lengthy works out there on Haskell? 

Maybe we could think of some pros and cons related to Plutus instead over time though instead of just general ones that other people already have come up with.

**Comment by dostrelith678** [comment]
Agreed 👍  Thanks for the feedback.

**Comment by dostrelith678** [comment]
Sections removed.
